In [1]:
import pandas as pd
import datetime as dt
from datetime import datetime
from datetime import timedelta

# read csv file
df = pd.read_csv("29286875.csv")

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [2]:
# change the column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df

,id,drone_type,post_type,package_weight,origin_region,destination_region,origin_latitude,origin_longitude,destination_latitude,destination_longitude,journey_distance,departure_date,departure_time,travel_time,delivery_time,delivery_fare
0,ID5174772222,2.0,1.0,43.632,47.0,3.0,-37.355446,145.140356,-36.683571,147.271147,203.610,2018-03-24,03:47:54,163.99,6:31:53,187.16
1,ID1302741470,2.0,0.0,14.230,42.0,45.0,-38.029425,146.072856,-38.880642,145.089798,127.756,2018-04-01,19:00:04,105.65,20:45:43,132.04
2,ID1271333154,1.0,0.0,31.700,19.0,8.0,-38.467031,144.056414,-37.882256,147.344381,294.983,2018-04-27,01:05:05,240.38,5:05:27,122.90
3,ID5399258418,2.0,1.0,11.500,7.0,48.0,-37.594913,147.765656,-38.942574,146.852666,169.915,2018-04-11,16:12:11,138.08,18:30:15,170.52
4,ID5288620287,1.0,1.0,14.545,28.0,4.0,-37.234915,144.722604,-37.682460,145.132520,61.595,2018-06-07,01:14:37,56.13,2:10:44,139.68
5,ID5993957587,2.0,1.0,33.332,9.0,24.0,-36.814897,144.334465,-38.966256,143.372101,253.963,2018-04-21,01:42:57,202.73,5:05:40,190.62
6,ID1175666777,3.0,0.0,14.360,34.0,46.0,-38.694757,144.574710,-37.414616,145.765778,176.649,2018-02-18,08:23:32,141.38,10:44:54,155.92
7,ID1247377835,1.0,0.0,16.681,21.0,4.0,-38.511416,148.229283,-37.934283,144.996650,289.890,2018-05-08,12:55:01,236.36,16:51:22,108.36
8,ID1727276208,1.0,0.0,7.631,21.0,4.0,-38.669030,147.959281,-37.785768,144.938933,281.808,2018-06-20,05:23:21,229.98,9:13:19,119.50
9,ID1656980587,1.0,0.0,41.862,33.0,24.0,-36.575290,143.945037,-38.903490,143.211961,267.079,2018-05-17,09:23:21,218.35,13:01:41,83.82
10,ID1229281063,3.0,0.0,36.585,40.0,18.0,-38.131144,147.937330,-38.907359,144.012057,352.587,2018-03-23,02:30:20,275.00,7:05:20,201.81
11,ID1430032672,3.0,0.0,44.666,7.0,43.0,-37.443194,147.796298,-38.065081,144.858493,267.656,2018-02-24,01:12:03,210.50,4:42:33,199.03
12,ID1422704796,1.0,0.0,33.833,39.0,15.0,-36.600640,145.855849,-38.053912,143.384933,272.028,2018-07-13,22:42:30,222.26,2:24:45,121.98
13,ID1814710120,3.0,0.0,22.782,5.0,19.0,-36.897139,146.128542,-38.479546,144.109594,250.305,2018-07-27,08:54:12,197.32,12:11:31,158.61
14,ID1144987939,2.0,0.0,23.153,10.0,41.0,-36.745948,147.879398,-38.146925,142.908804,466.072,2018-04-02,18:04:40,365.89,0:10:33,156.55
15,ID1639996043,1.0,0.0,39.888,48.0,12.0,-38.969324,147.020365,-37.506954,143.204698,371.170,2018-04-01,11:51:04,300.53,16:51:35,96.35
16,ID1589940287,2.0,0.0,42.803,12.0,25.0,-37.626460,143.160095,-37.768288,145.754603,229.061,2018-01-10,18:49:45,183.57,21:53:19,140.64
17,ID1700086850,1.0,0.0,40.017,12.0,49.0,-37.594545,143.097470,-38.276013,143.786223,97.011,2018-05-03,07:44:34,84.09,9:08:39,75.18
18,ID1816080840,3.0,0.0,41.875,14.0,45.0,-37.251321,146.656823,-38.979117,145.069270,237.317,2018-07-06,01:14:50,187.46,4:22:17,192.77
19,ID5188568054,1.0,1.0,42.657,46.0,39.0,-37.234876,145.879212,-36.523866,145.699468,80.749,2018-04-27,18:17:19,71.25,19:28:34,121.17
20,ID1693500629,1.0,0.0,30.022,46.0,45.0,-37.164073,145.679463,-38.898297,145.204466,197.489,2018-05-09,13:08:24,163.41,15:51:48,97.98
21,ID5483031848,2.0,1.0,41.371,20.0,37.0,-38.352655,146.411445,-36.642337,146.362691,190.436,2018-05-12,18:29:20,153.86,21:03:11,170.95
22,ID5902904752,3.0,1.0,6.951,31.0,45.0,-36.703164,148.134965,-38.858697,145.186198,353.345,2018-01-11,20:35:54,275.58,1:11:28,224.27
23,ID1133610304,1.0,0.0,35.364,33.0,15.0,-36.577901,143.726564,-37.963910,143.319938,158.435,2018-04-10,01:24:44,132.58,3:37:18,113.32
24,ID1388702296,1.0,0.0,19.875,4.0,24.0,-37.692200,144.965438,-38.860640,143.226976,199.985,2018-07-13,17:00:08,165.38,19:45:30,98.44
25,ID1936333571,1.0,0.0,42.657,48.0,7.0,-38.796754,146.893037,-37.548817,147.628529,153.102,2018-03-13,08:14:05,128.37,10:22:27,84.13
26,ID1369982920,1.0,0.0,6.635,30.0,25.0,-38.504116,143.250021,-37.631763,145.646796,231.398,2018-03-07,00:33:50,190.18,3:44:00,115.12
27,ID5871196450,3.0,1.0,32.778,41.0,40.0,-38.048797,142.827650,-38.195071,147.655284,423.036,2018-07-05,07:35:56,328.51,13:04:26,212.53
28,ID5876881006,3.0,1.0,18.442,30.0,4.0,-38.643890,143.128489,-37.711192,145.055515,198.020,2018-05-17,19:54:16,157.61,22:31:52,204.13
29,ID5229082212,1.0,1.0,12.185,19.0,15.0,-38.413642,144.233445,-37.928076,143.380033,92.192,2018-02-19,20:05:15,80.28,21:25:31,126.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39083,NaN,2.0,1.0,45.659,31.0,38.0,-36.786683,148.358368,-38.994020,147.564593,255.414,2018-03-26,08:54:45,203.84,12:18:35,160.17
39084,NaN,2.0,0.0,52.883,3.0,10.0,-36.553526,147.380237,-36.582356,147.861928,43.185,2018-02-11,20:51:18,40.59,21:31:53,201.16
39085,ID1808405020,2.0,0.0,14.292,48.0,44.0,-38.851248,146.947241,-36.892103,147.333852,220.716,2018-01-12,14:43:01,177.15,17:40:10,134.31
39086,ID1981588347,3.0,0.0,42.354,49.0,49.0,-38.248567,143.582063,-38.216528,143.490395,8.773,2018-04-10,05:28:09,13.88,5:42:01,170.26
39087,ID1852942304,1.0,0.0,14.525,1.0,30.0,-38.382072,145.283777,-38.554625,143.087968,192.335,2018-03-25,00:16:35,159.34,2:55:55,113.42
39088,NaN,2.0,0.0,36.948,7.0,28.0,-37.396605,147.763582,-37.150497,144.420712,297.363,2018-01-23,15:24:23,236.11,19:20:29,148.37
39089,NaN,2.0,0.0,20.302,38.0,49.0,-38.993133,147.308400,-38.219451,143.658456,328.951,2018-01-28,06:40:51,260.41,11:01:15,131.72
39090,NaN,2.0,0.0,5.659,21.0,2.0,-38.665408,148.150719,-37.012339,143.548243,444.416,2018-03-01,08:29:35,349.23,14:18:48,144.97
39091,NaN,1.0,0.0,31.260,44.0,34.0,-36.978581,147.188853,-38.548107,144.729877,278.102,2018-05-24,01:13:22,227.05,5:00:25,126.77
39092,ID1441436990,1.0,0.0,30.637,48.0,45.0,-38.841315,146.966196,-38.987929,145.102386,162.252,2018-06-28,13:46:25,135.59,16:02:00,102.02
39093,NaN,2.0,0.0,9.292,28.0,46.0,-37.073096,144.572825,-37.273451,145.684967,101.135,2018-04-03,17:31:04,85.17,18:56:14,126.99
39094,NaN,1.0,1.0,7.187,45.0,9.0,-39.005044,144.920018,-36.745070,144.333425,256.798,2018-03-24,01:27:22,210.23,4:57:35,151.88
39095,ID5190254409,1.0,1.0,14.354,33.0,8.0,-36.661443,143.740064,-37.921522,147.184127,335.683,2018-06-05,15:47:46,272.51,20:20:16,138.50
39096,NaN,1.0,0.0,44.714,34.0,11.0,-38.673199,144.543470,-37.871408,144.061367,98.697,2018-01-15,18:08:41,85.42,19:34:06,92.23
39097,ID1983083322,3.0,0.0,43.591,4.0,9.0,-37.776747,145.163297,-36.777164,144.516377,125.158,2018-02-11,22:47:34,102.27,0:29:50,186.75
39098,ID1314059119,1.0,0.0,14.472,32.0,24.0,-37.324911,144.064789,-38.966256,143.437232,190.789,2018-02-02,13:43:48,158.12,16:21:55,99.57
39099,ID1320771132,2.0,0.0,42.120,45.0,46.0,-38.837537,145.207474,-37.266695,145.871601,184.296,2018-01-26,15:13:49,149.14,17:42:57,136.37
39100,ID1258600582,1.0,0.0,5.143,10.0,47.0,-36.673197,147.696826,-37.562826,144.989465,259.907,2018-06-24,11:49:46,212.69,15:22:27,90.27
39101,NaN,2.0,1.0,29.509,29.0,46.0,-37.416182,148.369018,-37.303939,145.645094,241.325,2018-02-11,02:30:52,193.01,5:43:52,190.68
39102,ID1467220902,3.0,0.0,40.650,49.0,27.0,-38.314837,143.678639,-38.796300,146.415416,244.181,2018-01-10,19:28:31,192.67,22:41:11,177.37
39103,NaN,2.0,0.0,8.102,15.0,17.0,-38.040205,143.453953,-37.088197,145.408862,202.442,2018-03-27,14:40:45,163.10,17:23:50,135.41
39104,ID1233384783,1.0,0.0,20.208,36.0,25.0,-37.468151,146.691423,-37.703348,145.633240,96.946,2018-06-25,08:56:35,84.04,10:20:37,79.98
39105,NaN,1.0,1.0,39.785,12.0,29.0,-37.476126,142.944007,-37.351112,148.034551,450.245,2018-03-08,19:21:52,362.96,1:24:49,158.94
39106,NaN,1.0,0.0,39.698,48.0,3.0,-38.840722,146.784047,-36.647890,147.274896,247.893,2018-06-11,14:48:10,203.20,18:11:21,110.64
39107,ID1927939031,1.0,0.0,24.704,25.0,50.0,-37.767926,145.627710,-38.924650,142.796896,278.652,2018-03-03,12:24:43,227.49,16:12:12,110.15
39108,ID1164150997,2.0,0.0,40.174,5.0,6.0,-36.896320,145.965648,-37.640343,146.196588,85.312,2018-04-18,10:04:35,73.00,11:17:35,115.41
39109,ID5421234552,2.0,1.0,34.871,29.0,44.0,-37.331022,148.212160,-36.826330,147.283740,99.773,2018-02-17,20:05:32,84.12,21:29:39,165.43
39110,ID1918590566,3.0,0.0,25.669,9.0,5.0,-36.793014,144.315626,-36.918182,145.903194,142.088,2018-02-20,18:06:29,115.13,20:01:36,171.88
39111,NaN,1.0,1.0,34.102,26.0,45.0,-37.953956,148.363535,-38.988100,145.213628,297.660,2018-02-19,12:17:33,242.49,16:20:02,143.08
39112,NaN,3.0,0.0,43.956,9.0,30.0,-36.745070,144.333425,-38.421277,143.251229,209.590,2018-07-21,20:57:26,166.40,23:43:50,175.26

In [3]:
time_df = pd.DataFrame(df[['drone_type', 'departure_time', 'delivery_time', 'travel_time', 'journey_distance']], columns=['drone_type', 'departure_time', 'delivery_time', 'travel_time', 'journey_distance'])

In [4]:
time_df = time_df.dropna()
time_df = time_df.reset_index()

In [5]:
time_df['travel_time'].isnull().sum()

0

In [6]:
time_df

,index,drone_type,departure_time,delivery_time,travel_time,journey_distance
0,0,2.0,03:47:54,6:31:53,163.99,203.610
1,1,2.0,19:00:04,20:45:43,105.65,127.756
2,2,1.0,01:05:05,5:05:27,240.38,294.983
3,3,2.0,16:12:11,18:30:15,138.08,169.915
4,4,1.0,01:14:37,2:10:44,56.13,61.595
5,5,2.0,01:42:57,5:05:40,202.73,253.963
6,6,3.0,08:23:32,10:44:54,141.38,176.649
7,7,1.0,12:55:01,16:51:22,236.36,289.890
8,8,1.0,05:23:21,9:13:19,229.98,281.808
9,9,1.0,09:23:21,13:01:41,218.35,267.079
10,10,3.0,02:30:20,7:05:20,275.00,352.587
11,11,3.0,01:12:03,4:42:33,210.50,267.656
12,12,1.0,22:42:30,2:24:45,222.26,272.028
13,13,3.0,08:54:12,12:11:31,197.32,250.305
14,14,2.0,18:04:40,0:10:33,365.89,466.072
15,15,1.0,11:51:04,16:51:35,300.53,371.170
16,16,2.0,18:49:45,21:53:19,183.57,229.061
17,17,1.0,07:44:34,9:08:39,84.09,97.011
18,18,3.0,01:14:50,4:22:17,187.46,237.317
19,19,1.0,18:17:19,19:28:34,71.25,80.749
20,20,1.0,13:08:24,15:51:48,163.41,197.489
21,21,2.0,18:29:20,21:03:11,153.86,190.436
22,22,3.0,20:35:54,1:11:28,275.58,353.345
23,23,1.0,01:24:44,3:37:18,132.58,158.435
24,24,1.0,17:00:08,19:45:30,165.38,199.985
25,25,1.0,08:14:05,10:22:27,128.37,153.102
26,26,1.0,00:33:50,3:44:00,190.18,231.398
27,27,3.0,07:35:56,13:04:26,328.51,423.036
28,28,3.0,19:54:16,22:31:52,157.61,198.020
29,29,1.0,20:05:15,21:25:31,80.28,92.192
...,...,...,...,...,...,...
39033,39083,2.0,08:54:45,12:18:35,203.84,255.414
39034,39084,2.0,20:51:18,21:31:53,40.59,43.185
39035,39085,2.0,14:43:01,17:40:10,177.15,220.716
39036,39086,3.0,05:28:09,5:42:01,13.88,8.773
39037,39087,1.0,00:16:35,2:55:55,159.34,192.335
39038,39088,2.0,15:24:23,19:20:29,236.11,297.363
39039,39089,2.0,06:40:51,11:01:15,260.41,328.951
39040,39090,2.0,08:29:35,14:18:48,349.23,444.416
39041,39091,1.0,01:13:22,5:00:25,227.05,278.102
39042,39092,1.0,13:46:25,16:02:00,135.59,162.252
39043,39093,2.0,17:31:04,18:56:14,85.17,101.135
39044,39094,1.0,01:27:22,4:57:35,210.23,256.798
39045,39095,1.0,15:47:46,20:20:16,272.51,335.683
39046,39096,1.0,18:08:41,19:34:06,85.42,98.697
39047,39097,3.0,22:47:34,0:29:50,102.27,125.158
39048,39098,1.0,13:43:48,16:21:55,158.12,190.789
39049,39099,2.0,15:13:49,17:42:57,149.14,184.296
39050,39100,1.0,11:49:46,15:22:27,212.69,259.907
39051,39101,2.0,02:30:52,5:43:52,193.01,241.325
39052,39102,3.0,19:28:31,22:41:11,192.67,244.181
39053,39103,2.0,14:40:45,17:23:50,163.10,202.442
39054,39104,1.0,08:56:35,10:20:37,84.04,96.946
39055,39105,1.0,19:21:52,1:24:49,362.96,450.245
39056,39106,1.0,14:48:10,18:11:21,203.20,247.893
39057,39107,1.0,12:24:43,16:12:12,227.49,278.652
39058,39108,2.0,10:04:35,11:17:35,73.00,85.312
39059,39109,2.0,20:05:32,21:29:39,84.12,99.773
39060,39110,3.0,18:06:29,20:01:36,115.13,142.088
39061,39111,1.0,12:17:33,16:20:02,242.49,297.660
39062,39112,3.0,20:57:26,23:43:50,166.40,209.590

In [7]:
# extract hour
time_df['departure_hour'] = time_df['departure_time'].str.split(':').str[0]
# extract minute
time_df['departure_min'] = time_df['departure_time'].str.split(':').str[1]
# extract second
time_df['departure_second'] = time_df['departure_time'].str.split(':').str[2]

In [8]:
# extract hour
time_df['delivery_hour'] = time_df['delivery_time'].str.split(':').str[0]
# extract minute
time_df['delivery_min'] = time_df['delivery_time'].str.split(':').str[1]
# extract second
time_df['delivery_second'] = time_df['delivery_time'].str.split(':').str[2]

In [9]:
type(time_df.loc[1, 'delivery_hour'])

str

In [10]:
# time_df

In [11]:
# # 439/60 = 7.3 hrs 可以知道最大差距時間是七小時左右
# df[['travel_time']].describe()

In [12]:
# time_df[['travel_time']].describe()

In [13]:
# item() returns the first element of the underlying data as a python scalar
# type((time_df.loc[1, 'travel_time']*60).item())
# (time_df.loc[1, 'travel_time']*60).item()

In [14]:
# def a():
#     a = [1, 2, 3]
#     b = sum(a)/len(a)
#     return b

# print(a())

In [15]:
time_df

,index,drone_type,departure_time,delivery_time,travel_time,journey_distance,departure_hour,departure_min,departure_second,delivery_hour,delivery_min,delivery_second
0,0,2.0,03:47:54,6:31:53,163.99,203.610,03,47,54,6,31,53
1,1,2.0,19:00:04,20:45:43,105.65,127.756,19,00,04,20,45,43
2,2,1.0,01:05:05,5:05:27,240.38,294.983,01,05,05,5,05,27
3,3,2.0,16:12:11,18:30:15,138.08,169.915,16,12,11,18,30,15
4,4,1.0,01:14:37,2:10:44,56.13,61.595,01,14,37,2,10,44
5,5,2.0,01:42:57,5:05:40,202.73,253.963,01,42,57,5,05,40
6,6,3.0,08:23:32,10:44:54,141.38,176.649,08,23,32,10,44,54
7,7,1.0,12:55:01,16:51:22,236.36,289.890,12,55,01,16,51,22
8,8,1.0,05:23:21,9:13:19,229.98,281.808,05,23,21,9,13,19
9,9,1.0,09:23:21,13:01:41,218.35,267.079,09,23,21,13,01,41
10,10,3.0,02:30:20,7:05:20,275.00,352.587,02,30,20,7,05,20
11,11,3.0,01:12:03,4:42:33,210.50,267.656,01,12,03,4,42,33
12,12,1.0,22:42:30,2:24:45,222.26,272.028,22,42,30,2,24,45
13,13,3.0,08:54:12,12:11:31,197.32,250.305,08,54,12,12,11,31
14,14,2.0,18:04:40,0:10:33,365.89,466.072,18,04,40,0,10,33
15,15,1.0,11:51:04,16:51:35,300.53,371.170,11,51,04,16,51,35
16,16,2.0,18:49:45,21:53:19,183.57,229.061,18,49,45,21,53,19
17,17,1.0,07:44:34,9:08:39,84.09,97.011,07,44,34,9,08,39
18,18,3.0,01:14:50,4:22:17,187.46,237.317,01,14,50,4,22,17
19,19,1.0,18:17:19,19:28:34,71.25,80.749,18,17,19,19,28,34
20,20,1.0,13:08:24,15:51:48,163.41,197.489,13,08,24,15,51,48
21,21,2.0,18:29:20,21:03:11,153.86,190.436,18,29,20,21,03,11
22,22,3.0,20:35:54,1:11:28,275.58,353.345,20,35,54,1,11,28
23,23,1.0,01:24:44,3:37:18,132.58,158.435,01,24,44,3,37,18
24,24,1.0,17:00:08,19:45:30,165.38,199.985,17,00,08,19,45,30
25,25,1.0,08:14:05,10:22:27,128.37,153.102,08,14,05,10,22,27
26,26,1.0,00:33:50,3:44:00,190.18,231.398,00,33,50,3,44,00
27,27,3.0,07:35:56,13:04:26,328.51,423.036,07,35,56,13,04,26
28,28,3.0,19:54:16,22:31:52,157.61,198.020,19,54,16,22,31,52
29,29,1.0,20:05:15,21:25:31,80.28,92.192,20,05,15,21,25,31
...,...,...,...,...,...,...,...,...,...,...,...,...
39033,39083,2.0,08:54:45,12:18:35,203.84,255.414,08,54,45,12,18,35
39034,39084,2.0,20:51:18,21:31:53,40.59,43.185,20,51,18,21,31,53
39035,39085,2.0,14:43:01,17:40:10,177.15,220.716,14,43,01,17,40,10
39036,39086,3.0,05:28:09,5:42:01,13.88,8.773,05,28,09,5,42,01
39037,39087,1.0,00:16:35,2:55:55,159.34,192.335,00,16,35,2,55,55
39038,39088,2.0,15:24:23,19:20:29,236.11,297.363,15,24,23,19,20,29
39039,39089,2.0,06:40:51,11:01:15,260.41,328.951,06,40,51,11,01,15
39040,39090,2.0,08:29:35,14:18:48,349.23,444.416,08,29,35,14,18,48
39041,39091,1.0,01:13:22,5:00:25,227.05,278.102,01,13,22,5,00,25
39042,39092,1.0,13:46:25,16:02:00,135.59,162.252,13,46,25,16,02,00
39043,39093,2.0,17:31:04,18:56:14,85.17,101.135,17,31,04,18,56,14
39044,39094,1.0,01:27:22,4:57:35,210.23,256.798,01,27,22,4,57,35
39045,39095,1.0,15:47:46,20:20:16,272.51,335.683,15,47,46,20,20,16
39046,39096,1.0,18:08:41,19:34:06,85.42,98.697,18,08,41,19,34,06
39047,39097,3.0,22:47:34,0:29:50,102.27,125.158,22,47,34,0,29,50
39048,39098,1.0,13:43:48,16:21:55,158.12,190.789,13,43,48,16,21,55
39049,39099,2.0,15:13:49,17:42:57,149.14,184.296,15,13,49,17,42,57
39050,39100,1.0,11:49:46,15:22:27,212.69,259.907,11,49,46,15,22,27
39051,39101,2.0,02:30:52,5:43:52,193.01,241.325,02,30,52,5,43,52
39052,39102,3.0,19:28:31,22:41:11,192.67,244.181,19,28,31,22,41,11
39053,39103,2.0,14:40:45,17:23:50,163.10,202.442,14,40,45,17,23,50
39054,39104,1.0,08:56:35,10:20:37,84.04,96.946,08,56,35,10,20,37
39055,39105,1.0,19:21:52,1:24:49,362.96,450.245,19,21,52,1,24,49
39056,39106,1.0,14:48:10,18:11:21,203.20,247.893,14,48,10,18,11,21
39057,39107,1.0,12:24:43,16:12:12,227.49,278.652,12,24,43,16,12,12
39058,39108,2.0,10:04:35,11:17:35,73.00,85.312,10,04,35,11,17,35
39059,39109,2.0,20:05:32,21:29:39,84.12,99.773,20,05,32,21,29,39
39060,39110,3.0,18:06:29,20:01:36,115.13,142.088,18,06,29,20,01,36
39061,39111,1.0,12:17:33,16:20:02,242.49,297.660,12,17,33,16,20,02
39062,39112,3.0,20:57:26,23:43:50,166.40,209.590,20,57,26,23,43,50

In [16]:
type(int(time_df.loc[39061, 'index']))

int

In [17]:
# 測試調換出發時間跟到達時間後， 有沒有相同的travel time
wrong_time_row_lst = []
temp_lst = []
for row in range(len(time_df)):
    raw_s = int(time_df.loc[row, 'travel_time']*60)
    delivery_s = int(time_df.loc[row, 'delivery_hour'])*60*60 + int(time_df.loc[row, 'delivery_min'])*60 + int(time_df.loc[row, 'delivery_second'])
    departure_s = int(time_df.loc[row, 'departure_hour'])*60*60 + int(time_df.loc[row, 'departure_min'])*60 + int(time_df.loc[row, 'departure_second'])
    cal_s = delivery_s - departure_s # seconds
    result = raw_s - cal_s # 與 travel time 的誤差
#     print(row, raw_s, cal_s, result) # 在此的result顯示所有對跟錯的
    
    if result != 0: # 與 travel time 有誤差的 data 行數加到 list 中
        original_index = int(time_df.loc[row, 'index'])
        wrong_time_row_lst.append(original_index)
        temp_lst.append(row)

# #         print(row)    
#         '''1'''
#         if (raw_s/60/60) > 8: # 在這些正確的travel time中，找有沒有大於travel time max (單位：hrs)
#             print(row, raw_s, cal_s, result) # 發現應該都沒有不合理的（現在時間中有NaN，要把這段放回主程式碼去測試）
# #         else:
# #             print("Correct")
#     else: # 與 travel time 有誤差的 data 行數加到 list 中
#         wrong_time_row_lst.append(row)

In [18]:
wrong_time_row_lst

[9,
 12,
 14,
 22,
 43,
 47,
 53,
 54,
 61,
 67,
 78,
 81,
 82,
 101,
 105,
 108,
 110,
 121,
 149,
 153,
 157,
 158,
 159,
 166,
 171,
 191,
 195,
 201,
 207,
 216,
 242,
 246,
 247,
 265,
 269,
 276,
 283,
 284,
 305,
 307,
 308,
 326,
 332,
 335,
 336,
 337,
 353,
 360,
 380,
 387,
 388,
 398,
 400,
 403,
 409,
 414,
 415,
 416,
 422,
 434,
 436,
 437,
 442,
 443,
 447,
 448,
 449,
 451,
 452,
 461,
 466,
 474,
 475,
 477,
 479,
 483,
 486,
 499,
 504,
 506,
 513,
 514,
 520,
 521,
 526,
 530,
 531,
 532,
 555,
 563,
 564,
 569,
 575,
 577,
 582,
 583,
 584,
 593,
 614,
 621,
 629,
 632,
 636,
 642,
 648,
 662,
 681,
 683,
 686,
 691,
 696,
 699,
 702,
 708,
 709,
 713,
 717,
 721,
 722,
 726,
 734,
 748,
 767,
 768,
 769,
 771,
 777,
 781,
 786,
 789,
 800,
 802,
 805,
 807,
 808,
 811,
 817,
 830,
 836,
 843,
 846,
 850,
 855,
 856,
 861,
 873,
 875,
 877,
 879,
 883,
 885,
 890,
 896,
 911,
 923,
 925,
 928,
 936,
 941,
 944,
 950,
 961,
 967,
 977,
 983,
 989,
 1004,
 1006,
 1007,
 1008,
 1010,
 1025,
 1032,
 1034,
 1036,
 1037,
 1040,
 1051,
 1052,
 1063,
 1077,
 1085,
 1087,
 1092,
 1095,
 1097,
 1104,
 1108,
 1109,
 1117,
 1118,
 1127,
 1134,
 1153,
 1155,
 1165,
 1169,
 1172,
 1173,
 1182,
 1183,
 1194,
 1204,
 1211,
 1214,
 1222,
 1223,
 1240,
 1242,
 1247,
 1249,
 1250,
 1254,
 1256,
 1257,
 1259,
 1284,
 1285,
 1286,
 1299,
 1300,
 1306,
 1307,
 1321,
 1324,
 1326,
 1327,
 1335,
 1338,
 1357,
 1360,
 1381,
 1398,
 1409,
 1417,
 1426,
 1437,
 1450,
 1458,
 1466,
 1469,
 1477,
 1484,
 1491,
 1499,
 1503,
 1508,
 1513,
 1522,
 1523,
 1524,
 1533,
 1534,
 1537,
 1545,
 1552,
 1555,
 1560,
 1564,
 1567,
 1574,
 1576,
 1587,
 1589,
 1608,
 1614,
 1615,
 1621,
 1622,
 1624,
 1625,
 1628,
 1642,
 1659,
 1662,
 1663,
 1665,
 1670,
 1672,
 1674,
 1675,
 1678,
 1681,
 1682,
 1689,
 1696,
 1702,
 1707,
 1716,
 1717,
 1723,
 1724,
 1735,
 1744,
 1753,
 1756,
 1758,
 1763,
 1765,
 1767,
 1776,
 1779,
 1788,
 1790,
 1792,
 1796,
 1797,
 1813,
 1814,
 1817,
 1820,
 1822,
 1825,
 1838,
 1846,
 1847,
 1863,
 1870,
 1876,
 1878,
 1879,
 1881,
 1903,
 1914,
 1919,
 1925,
 1928,
 1930,
 1936,
 1944,
 1947,
 1953,
 1960,
 1961,
 1963,
 1966,
 1973,
 1985,
 1987,
 1991,
 1996,
 2007,
 2009,
 2010,
 2021,
 2022,
 2028,
 2029,
 2035,
 2038,
 2047,
 2048,
 2052,
 2056,
 2064,
 2066,
 2099,
 2104,
 2106,
 2109,
 2114,
 2117,
 2120,
 2130,
 2151,
 2158,
 2166,
 2172,
 2182,
 2183,
 2186,
 2209,
 2214,
 2218,
 2224,
 2225,
 2228,
 2234,
 2236,
 2237,
 2241,
 2242,
 2246,
 2250,
 2252,
 2254,
 2255,
 2258,
 2262,
 2263,
 2267,
 2270,
 2275,
 2280,
 2286,
 2287,
 2289,
 2294,
 2302,
 2312,
 2315,
 2319,
 2330,
 2335,
 2341,
 2353,
 2362,
 2364,
 2368,
 2370,
 2381,
 2382,
 2383,
 2392,
 2394,
 2395,
 2396,
 2398,
 2400,
 2404,
 2406,
 2407,
 2409,
 2410,
 2416,
 2421,
 2427,
 2438,
 2441,
 2454,
 2458,
 2460,
 2463,
 2495,
 2516,
 2526,
 2529,
 2540,
 2546,
 2556,
 2562,
 2563,
 2570,
 2572,
 2576,
 2577,
 2587,
 2593,
 2596,
 2602,
 2603,
 2616,
 2628,
 2631,
 2633,
 2634,
 2639,
 2643,
 2649,
 2654,
 2655,
 2664,
 2679,
 2680,
 2690,
 2691,
 2701,
 2705,
 2706,
 2717,
 2719,
 2729,
 2733,
 2737,
 2743,
 2744,
 2745,
 2751,
 2756,
 2766,
 2784,
 2795,
 2798,
 2803,
 2806,
 2809,
 2828,
 2831,
 2832,
 2833,
 2840,
 2844,
 2854,
 2855,
 2859,
 2860,
 2877,
 2882,
 2884,
 2887,
 2895,
 2896,
 2897,
 2898,
 2905,
 2915,
 2924,
 2927,
 2929,
 2937,
 2947,
 2950,
 2953,
 2955,
 2957,
 2958,
 2963,
 2966,
 2971,
 2989,
 3002,
 3006,
 3012,
 3025,
 3033,
 3040,
 3042,
 3043,
 3048,
 3056,
 3059,
 3065,
 3066,
 3069,
 3074,
 3078,
 3082,
 3094,
 3096,
 3101,
 3104,
 3118,
 3120,
 3123,
 3128,
 3140,
 3144,
 3147,
 3149,
 3152,
 3155,
 3156,
 3168,
 3174,
 3177,
 3183,
 3185,
 3186,
 3190,
 3191,
 3195,
 3208,
 3210,
 3213,
 3219,
 3220,
 3224,
 3231,
 3233,
 3240,
 3265,
 3270,
 3275,
 3277,
 3280,
 3284,
 3291,
 3294,
 3295,
 3302,
 3308,
 3314,
 3316,
 3317,
 3323,
 3328,
 3332,
 3334,
 3336,
 3339,
 3340,
 3344,
 3345,
 3351,
 3358,
 3362,
 3363,
 3364,
 3365,
 3366,
 3367,
 3378,
 3383,
 3389,
 3394,
 3403,
 3414,
 3425,
 3427,
 3430,
 3435,
 3440,
 3441,
 3446,
 3447,
 3451,
 3462,
 3475,
 3481,
 3483,
 3484,
 3496,
 3498,
 3499,
 3501,
 3502,
 3513,
 3514,
 3521,
 3522,
 3533,
 3537,
 3543,
 3548,
 3556,
 3563,
 3564,
 3568,
 3579,
 3584,
 3594,
 3595,
 3598,
 3599,
 3613,
 3615,
 3622,
 3625,
 3631,
 3636,
 3638,
 3641,
 3643,
 3655,
 3666,
 3677,
 3679,
 3686,
 3692,
 3694,
 3696,
 3703,
 3706,
 3713,
 3714,
 3730,
 3731,
 3733,
 3748,
 3753,
 3768,
 3775,
 3781,
 3791,
 3794,
 3795,
 3798,
 3808,
 3818,
 3823,
 3834,
 3835,
 3837,
 3838,
 3839,
 3841,
 3842,
 3849,
 3858,
 3864,
 3865,
 3869,
 3873,
 3876,
 3884,
 3892,
 3897,
 3898,
 3912,
 3914,
 3918,
 3920,
 3921,
 3937,
 3939,
 3945,
 3950,
 3952,
 3956,
 3966,
 3978,
 3979,
 3987,
 3990,
 3997,
 4007,
 4008,
 4011,
 4017,
 4018,
 4019,
 4026,
 4034,
 4035,
 4036,
 4037,
 4045,
 4059,
 4071,
 4074,
 4082,
 4084,
 4085,
 4128,
 4129,
 4132,
 4139,
 4143,
 4145,
 4153,
 4161,
 4164,
 4169,
 4175,
 4176,
 4177,
 4187,
 4189,
 4196,
 4198,
 4204,
 4210,
 4215,
 4216,
 4217,
 4218,
 4219,
 4228,
 4240,
 4243,
 4254,
 4259,
 4260,
 4261,
 4264,
 4265,
 4284,
 4285,
 4304,
 4308,
 4316,
 4320,
 4328,
 4331,
 4333,
 4340,
 4341,
 4342,
 4343,
 4352,
 4355,
 4361,
 4363,
 4364,
 4366,
 4368,
 4380,
 4396,
 4398,
 4399,
 4404,
 4405,
 4417,
 4419,
 4421,
 4425,
 4430,
 4431,
 4433,
 4450,
 4452,
 4464,
 4465,
 4474,
 4478,
 4481,
 4482,
 4485,
 4493,
 4505,
 4508,
 4524,
 4528,
 4536,
 4537,
 4542,
 4547,
 4548,
 4551,
 4554,
 4559,
 4563,
 4568,
 4569,
 4571,
 4578,
 4594,
 4605,
 4608,
 4612,
 4616,
 4621,
 4623,
 4627,
 4628,
 4646,
 4655,
 4661,
 4664,
 4671,
 4679,
 4683,
 4689,
 4694,
 4700,
 4717,
 4745,
 4746,
 4751,
 4754,
 4770,
 4772,
 4775,
 4780,
 4784,
 4787,
 4798,
 4815,
 4824,
 4827,
 4831,
 4837,
 4838,
 4843,
 4846,
 4851,
 4852,
 4855,
 4856,
 4857,
 4872,
 4882,
 4902,
 4906,
 4908,
 4909,
 4914,
 4918,
 4921,
 4922,
 4926,
 4935,
 4936,
 4937,
 4938,
 4940,
 4944,
 4954,
 4956,
 4957,
 4961,
 4964,
 4967,
 4972,
 4975,
 4982,
 4983,
 4988,
 4993,
 4994,
 4995,
 5002,
 5011,
 5017,
 5018,
 5020,
 5023,
 5024,
 5030,
 5031,
 5033,
 5037,
 5042,
 5048,
 5050,
 5051,
 5053,
 5059,
 5066,
 5072,
 5073,
 5077,
 5082,
 5083,
 5088,
 5092,
 5095,
 5108,
 5112,
 5117,
 5123,
 5124,
 5134,
 5139,
 5147,
 5150,
 5159,
 5163,
 5171,
 5174,
 5176,
 5177,
 5179,
 5181,
 5202,
 5215,
 5222,
 5231,
 5249,
 5251,
 5266,
 5270,
 5271,
 5274,
 5276,
 5278,
 5284,
 5290,
 5296,
 5300,
 5302,
 5307,
 5313,
 5318,
 5327,
 5328,
 5339,
 5340,
 5354,
 5358,
 5364,
 5366,
 5369,
 5372,
 5382,
 5384,
 5385,
 5386,
 5388,
 5392,
 5402,
 5404,
 5408,
 5411,
 5416,
 5419,
 5429,
 5430,
 5431,
 5436,
 5439,
 5451,
 5455,
 5459,
 5467,
 5471,
 5478,
 5483,
 5490,
 5492,
 ...]

In [19]:
# for calculating the more accurate average speed, so I need to drop the row with the wrong time
# extract the correct time to a new data frame and reset the index
correct_time_df = time_df.drop(temp_lst)
correct_time_df = correct_time_df.reset_index(drop=True)  
# correct_time_df

In [20]:
# average_distance = correct_time_df['journey_distance'].mean()
# average_time = (correct_time_df['travel_time'].mean())/60 # hour
# average_speed = average_distance/average_time
# print("The average distance:", average_distance, "\nThe average time:", average_time)
# print(average_speed)

In [21]:
# get the different speed of 3 drone types
drone1_df = correct_time_df.loc[correct_time_df['drone_type'] == 1, ['drone_type', 'journey_distance', 'travel_time']]
drone1_df = drone1_df.reset_index()
# drone1_df

drone2_df = correct_time_df.loc[correct_time_df['drone_type'] == 2, ['drone_type', 'journey_distance', 'travel_time']]
drone2_df = drone2_df.reset_index()

drone3_df = correct_time_df.loc[correct_time_df['drone_type'] == 3, ['drone_type', 'journey_distance', 'travel_time']]
drone3_df = drone3_df.reset_index()

def get_z_list(df):
    average_distance = df['journey_distance'].mean()
    average_time = (df['travel_time'].mean())/60 # hour
    average_speed = average_distance/average_time
    return average_speed

print("The average speed of drone type 1 (km/hr):", get_z_list(drone1_df),
      "\nThe average speed of drone type 2 (km/hr):", get_z_list(drone2_df),
      "\nThe average speed of drone type 3 (km/hr):", get_z_list(drone3_df))

The average speed of drone type 1 (km/hr): 72.68423819734582
The average speed of drone type 2 (km/hr): 74.51058078649106
The average speed of drone type 3 (km/hr): 75.5278078057149

In [22]:
# df

##### drone 1
gap: 0~8

In [23]:
# drone1 都差 0~8 左右
print(df.loc[2, 'travel_time'])
print((df.loc[2, 'journey_distance']/72.68423819734582)*60)

240.38
243.5050629814031

In [24]:
# drone1 都差 0~8 左右
print(df.loc[19, 'travel_time'])
print((df.loc[19, 'journey_distance']/72.68423819734582)*60)

71.25
66.65736781673968

In [25]:
# drone1 都差 0~8 左右
print(df.loc[39087, 'travel_time'])
print((df.loc[39087, 'journey_distance']/72.68423819734582)*60)

159.34
158.77032333567755

In [26]:
# drone2_df

##### drone 2
gap: < 8

In [27]:
# drone2
print(df.loc[0, 'travel_time'])
print((df.loc[0, 'journey_distance']/74.51058078649106)*60)

163.99
163.9579220970842

In [28]:
# drone2
print(df.loc[3, 'travel_time'])
print((df.loc[3, 'journey_distance']/74.51058078649106)*60)

138.08
136.82486289045755

In [29]:
# drone2
print(df.loc[21, 'travel_time'])
print((df.loc[21, 'journey_distance']/74.51058078649106)*60)

153.86
153.34949586209086

In [30]:
# drone3_df

##### drone 3
gap: < 8

In [31]:
# drone3
print(df.loc[39086, 'travel_time'])
print((df.loc[39086, 'journey_distance']/75.5278078057149)*60)

13.88
6.969353610183438

In [32]:
# drone3
print(df.loc[31764, 'travel_time'])
print((df.loc[31764, 'journey_distance']/75.5278078057149)*60)

371.81
376.3689272317141

In [33]:
df.loc[15188]

id                       ID5262085074
drone_type                          1
post_type                           1
package_weight                 45.439
origin_region                      30
destination_region                  7
origin_latitude              -38.5458
origin_longitude              143.269
destination_latitude         -37.4432
destination_longitude         147.796
journey_distance              415.673
departure_date             2018-03-17
departure_time               13:00:44
travel_time                    335.66
delivery_time                07:25:05
delivery_fare                  137.51
Name: 15188, dtype: object

In [34]:
df.loc[12]

id                       ID1422704796
drone_type                          1
post_type                           0
package_weight                 33.833
origin_region                      39
destination_region                 15
origin_latitude              -36.6006
origin_longitude              145.856
destination_latitude         -38.0539
destination_longitude         143.385
journey_distance              272.028
departure_date             2018-07-13
departure_time               22:42:30
travel_time                    222.26
delivery_time                 2:24:45
delivery_fare                  121.98
Name: 12, dtype: object

In [35]:
df.loc[1555]

id                       ID1708482665
drone_type                          1
post_type                           0
package_weight                 26.314
origin_region                      29
destination_region                 10
origin_latitude              -37.3833
origin_longitude              148.393
destination_latitude         -36.6267
destination_longitude         147.698
journey_distance              104.446
departure_date             2018-01-04
departure_time               22:42:07
travel_time                     89.96
delivery_time                 0:12:04
delivery_fare                  111.55
Name: 1555, dtype: object

In [36]:
# def compare_gap(drone_type):
#     average_time1 = (distance / drone1_speed)*60
#                 gap_raw = abs(average_time1 - raw_s/60)
#                 gap_cal = abs(average_time1 - cal_s/60)
# #                 print(row, average_time, gap_raw, gap_cal)
#                 # 比較差距，看誰差距小就比較正確
#                 if gap_raw < gap_cal: # original data is correct
#                     # departure + travel_time
#                     FMT = '%H:%M:%S'
#                     second = datetime.strptime(time_df.loc[row, 'departure_time'], FMT) + dt.timedelta(seconds=raw_s)
#                     df.at[original_index, 'delivery_time'] = second.time()
# #                     time_df.loc[original_index, 'delivery_time'] = second.time()
# #                     print(str(time))
# #                 else: # calculated data is correct
# #                     print(gap_raw) # departure + cal_time

In [37]:
count = 0
for row in temp_lst:
    raw_s = int(time_df.loc[row, 'travel_time']*60)
    # swap the departure time and delivery time here
    departure_s = int(time_df.loc[row, 'delivery_hour'])*60*60 + int(time_df.loc[row, 'delivery_min'])*60 + int(time_df.loc[row, 'delivery_second'])
    delivery_s = int(time_df.loc[row, 'departure_hour'])*60*60 + int(time_df.loc[row, 'departure_min'])*60 + int(time_df.loc[row, 'departure_second'])
    cal_s = delivery_s - departure_s # seconds
    result = raw_s - cal_s # 與 travel time 的誤差
#     print("Row", row, "; travel time:", raw_s, "; calculated time:", cal_s, "; gap:", result)
    
    
    drone1_speed = 72.68423819734582
    drone2_speed = 74.51058078649106
    drone3_speed = 75.5278078057149
    
        
    '''2''' # （if）這些就是出發時間跟到達時間需要交換的（兩個時間放反了）
    '''3''' # （else）這些就是有誤差且travel time又很大的資料
    original_index = time_df.loc[row, 'index']
    if result == 0: 
        # swap departure time & delivery time
        df.loc[original_index, 'departure_time'],  df.loc[original_index, 'delivery_time'] = df.loc[original_index, 'delivery_time'],  df.loc[original_index, 'departure_time']
    else: 
        '''first check'''
#         print("\nRow", original_index, "; travel time(s):", raw_s, "; calculated time(s):", cal_s, "; gap(s):", result)
#         print("The total minutes of each travel time", abs(cal_s)/60) # 從output可以看出有些值只差一秒，可以視為正確時間 
        if (raw_s + cal_s) != 1: # 等於1表示正確，且出發跟到達時間位置正確，差距慎小(不等於1才要進一步處理)
            '''second check'''
#             print("\nRow", original_index, "; travel time(s):", raw_s, "; calculated time(s):", cal_s, "; gap(s):", result)
#             print("The total minutes of each travel time", abs(cal_s)/60) 
            # swap departure time & delivery time
            df.loc[original_index, 'departure_time'],  df.loc[original_index, 'delivery_time'] = df.loc[original_index, 'delivery_time'],  df.loc[original_index, 'departure_time']
            # raw_s vs cal_s
            distance = time_df.loc[row, 'journey_distance']
            get_drone = time_df.loc[row, 'drone_type']
            if get_drone == 1: # drone type 1
                average_time1 = (distance / drone1_speed)*60
                gap_raw = abs(average_time1 - raw_s/60)
                gap_cal = abs(average_time1 - cal_s/60)
#                 print(row, average_time, gap_raw, gap_cal)
                # 比較差距，看誰差距小就比較正確
                if gap_raw < gap_cal: # original data is correct
                    # departure + travel_time
                    FMT = '%H:%M:%S'
                    second = (datetime.strptime(df.loc[original_index, 'departure_time'], FMT) + dt.timedelta(seconds=raw_s)).time()
                    df.at[original_index, 'delivery_time'] = second
#                     time_df.loc[original_index, 'delivery_time'] = second.time()
#                     print(str(time))
#                 else: # calculated data is correct
#                     print(gap_raw) # departure + cal_time
#             elif get_drone == 2: # drone type 2
#                 average_time2 = (distance / drone2_speed)*60
#                 gap_raw = abs(average_time2 - raw_s/60)
#                 gap_cal = abs(average_time2 - cal_s/60)
#                 if gap_raw < gap_cal: # original data is correct
#                     print(gap_cal) # departure + travel_time
#                 else: # calculated data is correct
#                     print(gap_raw) # departure + cal_time
#             else:
#                 average_time3 = (distance / drone3_speed)*60
#                 gap_raw = abs(average_time3 - raw_s/60)
#                 gap_cal = abs(average_time4 - cal_s/60)
#                 if gap_raw < gap_cal: # original data is correct
#                     print(gap_cal) # departure + travel_time
#                 else: # calculated data is correct
#                     print(gap_raw) # departure + cal_time



# print("There are " + str(count) + " data of the departure time needing to be swapped with the data of the delivery time.") # 發現32筆

In [38]:
df.loc[15188]

id                       ID5262085074
drone_type                          1
post_type                           1
package_weight                 45.439
origin_region                      30
destination_region                  7
origin_latitude              -38.5458
origin_longitude              143.269
destination_latitude         -37.4432
destination_longitude         147.796
journey_distance              415.673
departure_date             2018-03-17
departure_time               07:25:05
travel_time                    335.66
delivery_time                13:00:44
delivery_fare                  137.51
Name: 15188, dtype: object

In [39]:
df.loc[12]

id                       ID1422704796
drone_type                          1
post_type                           0
package_weight                 33.833
origin_region                      39
destination_region                 15
origin_latitude              -36.6006
origin_longitude              145.856
destination_latitude         -38.0539
destination_longitude         143.385
journey_distance              272.028
departure_date             2018-07-13
departure_time                2:24:45
travel_time                    222.26
delivery_time                06:07:00
delivery_fare                  121.98
Name: 12, dtype: object

In [40]:
df.loc[1555]

id                       ID1708482665
drone_type                          1
post_type                           0
package_weight                 26.314
origin_region                      29
destination_region                 10
origin_latitude              -37.3833
origin_longitude              148.393
destination_latitude         -36.6267
destination_longitude         147.698
journey_distance              104.446
departure_date             2018-01-04
departure_time                0:12:04
travel_time                     89.96
delivery_time                01:42:01
delivery_fare                  111.55
Name: 1555, dtype: object

In [41]:
# # x + y (the speed of takeOff & landing)
# (drone1_df.loc[1345, 'journey_distance'] - (drone1_df.loc[1345, 'travel_time'] - 10)*1.266)*12

In [42]:
# time_df.loc[[2853]]
# time_df.loc[[4932]]
# time_df.loc[[5065]]
# time_df.loc[[6955]]
# time_df.loc[[9031]]

In [43]:
# wrong_time_row_lst = []
# for row in range(len(time_df)):
#     raw_time = time_df.loc[row, 'travel_time'].item() # mins
#     delivery_s = int(time_df.loc[row, 'delivery_hour'])*60*60 + int(time_df.loc[row, 'delivery_min'])*60 + int(time_df.loc[row, 'delivery_second'])
#     departure_s = int(time_df.loc[row, 'departure_hour'])*60*60 + int(time_df.loc[row, 'departure_min'])*60 + int(time_df.loc[row, 'departure_second'])
#     cal_min = round((delivery_s - departure_s)/60, 2) # mins
#     result = round((raw_time - cal_min), 2)
# #     print(row, (delivery_s - departure_s)/60)
# #     print(result)
#     print(row, raw_time, cal_min, result)
# #     print(type(raw_time.item()), type(cal_second))
# #     if (result) > 0.02:
# #         wrong_time_row_lst.append(row)
# #         print(row, raw_time, cal_min, result) # 發現都多了2天 (1440mins/60mins/12hrs = 2days)
# # correct_time_df = time_df.drop(wrong_time_row_lst) # 先把錯的時間（差距太大的時間duration）移除
# # correct_time_df = correct_time_df.reset_index()
# # correct_time_df

# # # 抓準確的平均速度，之後方便求出準確的時間（因為現在距離確定是對的）
# # speed_lst = []
# # for index in range(len(correct_time_df)):
# #     d = correct_time_df.loc[index, 'journey_distance']
# #     t = correct_time_df.loc[index, 'travel_time']
# #     s = d/t
# #     speed_lst.append(s)

# # correct_time_df['average_speed'] = speed_lst
# # check_speed_df = correct_time_df[['index',  'drone_type','average_speed']] # 發現速度平均值是1.2
# # check_speed_df

In [44]:
import datetime as dt
from datetime import datetime
from datetime import timedelta

FMT = '%H:%M:%S'
second = (datetime.strptime('03:47:54', FMT) + dt.timedelta(seconds=9839.9)).time()
print(str(second))

06:31:53.900000